sonar.projectKey=Benjamin-003_DataVest-frontend
sonar.organization=benjamin-003

sonar.sources=src
sonar.tests=src

sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/*.cy.ts
sonar.test.inclusions=**/*.spec.ts