sonar.projectKey=Benjamin-003_DataVest-frontend
sonar.organization=benjamin-003

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/*.cy.ts

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Coverage Karma/Jasmine (format lcov, généré par Karma)
sonar.javascript.lcov.reportPaths=../../coverage/apps/frontend/lcov.info
sonar.typescript.lcov.reportPaths=../../coverage/apps/frontend/lcov.info