sonar.projectKey=Benjamin-003_DataVest-backend
sonar.organization=benjamin-003

sonar.sources=src
sonar.tests=src

sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,**/generated/**,prisma/**,src/index.ts,src/**/*.routes.ts,src/types/**,src/prisma/client.ts,src/config/rss-feeds.ts
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info