sonar.projectKey=Benjamin-003_DataVest-backend
sonar.organization=benjamin-003

sonar.sources=src
sonar.tests=src

sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/generated/**
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts