sonar.projectKey=Benjamin-003_DataVest-backend
sonar.organization=benjamin-003

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/generated/**

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

# Coverage Vitest (format lcov)
sonar.javascript.lcov.reportPaths=../../coverage/apps/backend/lcov.info
sonar.typescript.lcov.reportPaths=../../coverage/apps/backend/lcov.info